on:
  workflow_dispatch:
    inputs:
      os:
        description: '系统'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
      
      port:
        description: '端口'
        required: true
        default: '9000'
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

run-name: '${{ inputs.os }} ${{ inputs.port }}'

env:
  TZ: Asia/Shanghai

jobs:
  job:
    runs-on: ${{ contains(inputs.os, ':gui') && 'ubuntu-latest' || inputs.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Write to frpc.toml
        shell: bash
        run: |
          cat << EOF > frpc.toml
          user = "VirtualMachine"

          serverAddr = "43.135.40.161"
          serverPort = 7000
          loginFailExit = true

          auth.method = "token"
          auth.token = "2f1d3a0e-9b64-4b91-b76b-8cb4a2f2e5d3"

          [[proxies]]
          name = "fiddler"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 8866
          remotePort = 8866

          [[proxies]]
          name = "rdp${{ inputs.port }}"
          type = "tcp"
          localIP = "${{ runner.os == 'Windows' && '127.0.0.1' || '172.17.0.1' }}"
          localPort = 1234
          remotePort = ${{ inputs.port }}

          EOF

          if [[ "$RUNNER_OS" != "Windows" ]]; then
          cat << EOF >> frpc.toml
          [[proxies]]
          name = "ss"
          type = "tcp"
          localIP = "172.17.0.1"
          localPort = 8388
          remotePort = 8389
          EOF
          fi

      - name: 运行Linux
        if: ${{ runner.os == 'Linux' }}
        run: | 
          # 修改或添加 PasswordAuthentication yes
          grep -q '^#\?PasswordAuthentication' /etc/ssh/sshd_config \
            && sudo sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config \
            || echo 'PasswordAuthentication yes' | sudo tee -a /etc/ssh/sshd_config

          grep -q '^#\?PasswordAuthentication' /etc/ssh/sshd_config.d/*.conf \
            && sudo sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config.d/*.conf \
            || echo 'PasswordAuthentication yes' | sudo tee -a /etc/ssh/sshd_config.d/*.conf
          
          sudo systemctl restart ssh

          echo "runner:mynewpassword" | sudo chpasswd

          docker run -d --name frpc -v ./frpc.toml:/etc/frp/frpc.toml snowdreamtech/frpc
          
          # docker run -d \
          #   --name socks5-proxy \
          #   --restart unless-stopped \
          #   -p 1080:1080 \
          #   -e PROXY_USER=proxyuser \
          #   -e PROXY_PASSWORD=4d21b3bb-4186-4a9d-8448-510b4dae395f \
          #   serjs/go-socks5-proxy

          docker run -d \
            --restart unless-stopped \
            -p 8388:8388/tcp \
            -p 8388:8388/udp \
            -e TZ=Asia/Shanghai \
            -e METHOD=aes-256-gcm \
            -e PASSWORD=6a17a5dd-5f76-4b09-b567-9b0d5d449da5 \
            shadowsocks/shadowsocks-libev

          if [[ "${{ inputs.os }}" != *":gui" ]]; then
            docker run -d -p 1234:1234 --restart=always alpine/socat TCP-LISTEN:1234,fork TCP:172.17.0.1:22
            docker logs -f frpc
          fi

     
